version: '3.5'
services:
    web:
        build: ./web
        expose:
            - '8082'
        environment:
            ALIAS: '/'
            PORT: '8082'
        depends_on:
            - db
        restart: always
        networks:
            - proxy
            - backend
    db:
        build: ./db
        ports:
            - '3306'
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
        restart: always
        networks:
            - backend
volumes:
    db:

networks:
    proxy:
        name: nginx_reverse_proxy
    backend:
